### ISSUE TITLE
NumberFormatException on LocationResolverRdbmsTest for Mapped IPv4 address

### ISSUE THREAD

**Issue by ruwanta** [wso2/shared-analytics#150]
The following exception thrown for mapped IPv6 address with format ::ffff:192.168.2.1

java.lang.NumberFormatException: For input string: "::ffff:192"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getIpV4ToLong(LocationResolverRdbms.java:181)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getLocationFromLongValueOfIp(LocationResolverRdbms.java:104)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getLocationFromIp(LocationResolverRdbms.java:135)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getLocation(LocationResolverRdbms.java:61)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbmsTest.testGetLocation(LocationResolverRdbmsTest.java:116)

**Comment by ruwanta** [comment]
Fixed with commit ID 6c9962bb95c0b08c8c31eec5fba98d50a3de0c95 
Tests are added LocationResolverRdbmsTest.java
