### ISSUE TITLE
API Manager Geo Location Stats break when client IP is in CIDR format (eg. 10.100.0.2/24)

### ISSUE THREAD

**Issue by bhathiya** [wso2/shared-analytics#153]
**Description:**
API Manager Geo Location Stats break when client IP is in CIDR format (eg. 10.100.0.2/24).

```
TID: [-1] [] [2017-11-06 22:44:30,159]  WARN {org.apache.spark.scheduler.TaskSetManager} -  Lost task 2.0 in stage 356089.0 (TID 311137, platform-default-dasanalyzer-01): java.lang.Exception: Error while invoking method: getCountry, null
	at org.wso2.carbon.analytics.spark.core.udf.adaptor.UDF1Adaptor.call(UDF1Adaptor.java:64)
	at org.apache.spark.sql.UDFRegistration$$anonfun$register$25$$anonfun$apply$1.apply(UDFRegistration.scala:422)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.processInputs(TungstenAggregationIterator.scala:514)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregationIterator.<init>(TungstenAggregationIterator.scala:686)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:95)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:86)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "70/32"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getIpV4ToLong(LocationResolverRdbms.java:181)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getLocationFromLongValueOfIp(LocationResolverRdbms.java:104)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getLocationFromIp(LocationResolverRdbms.java:135)
	at org.wso2.carbon.analytics.shared.geolocation.impl.LocationResolverRdbms.getLocation(LocationResolverRdbms.java:61)
	at org.wso2.carbon.analytics.shared.geolocation.impl.GeoLocationResolverUDF.getCountry(GeoLocationResolverUDF.java:43)
	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.wso2.carbon.analytics.spark.core.udf.adaptor.UDF1Adaptor.call(UDF1Adaptor.java:60)
	... 21 more

```
**Affected Product Version:**

APIM Analytics 2.1.0 

**Steps to reproduce:**
1. Enable Geo Location stats in APIM
2. Create an API and call it with `X-Forwarded-For` header in CIDR format.

This breaks Geo Stats and print above error log.

**Comment by bhathiya** [comment]
Duplicate https://wso2.org/jira/browse/ANLYAPIM-170
